module.exports = {
  rootDir: './',
  collectCoverage: true,
  collectCoverageFrom: [
    'src/checkPasswordStrength.js',
    'src/cart_test.js',
    'src/checkoutTotal.js',
    'src/clearCart.js',
    'src/validateCardDetails.js',
    'src/OrderStatus.js',
    'src/Api_GET.js',
    'src/firebase/addToCart.js',
    'src/firebase/uploadImage.js',
    'src/firebase/removeFromCart.js',
    'src/firebase/firebase.js',
    '!**/node_modules/**',
    '!src/reportWebVitals.js',
    '!src/setupTests.js',
  ],
  coverageReporters: ['lcov', 'text'],
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
  testEnvironment: 'node',
  setupFilesAfterEnv: ['./src/setupTests.js'],
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
  },
  testMatch: ['<rootDir>/tests/**/*.test.js'],
};